### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by HeathJHMoore** [nss-evening-cohort-9/StudentLoansBangazon.UI#3]
## User Story
As a User, when I navigate anywhere in the application, I see a Navbar component at the top of the page. The Navbar should contain the following items: 
 * /Home /Login / --- when signed out
 * /Home /MyProfile /LogOut --- when signed in

When I click Log In, I should be logged in and taken to the /MyHome route

When I click Log Out, I should be logged out and taken to the /Home route

## Development
* Install react-strap
* In the Components folder, create a new folder called Navbar with a Navbar.js and Navbar.scss in it
* Reference Old project to figure out code for Navbar (ie how to reroute people to on button clicks, etc.)
* Finally, place the Navbar component in the App.js file outside of the Public and Private Routes (again reference old project for guidance)

**Comment by matthewaustinbell** [comment]
the navbar will have the follwing routes displayed
/Home /Login / --- when signed out
/Home /MyProfile /LogOut --- when signed in

(pass state from app.js have terinary in the product compent if your not authed you can rent.
